import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CustomizationProvider } from "@/lib/hooks/useCustomization";

/**
 * Primary sans-serif font - Inter
 * Clean, modern, highly legible at all sizes
 */
const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap", // Prevent FOUT
});

/**
 * Geist Sans - Vercel's design system font
 * Modern, geometric, excellent for UI
 */
const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
  display: "swap",
});

/**
 * Geist Mono - For timestamps, code, technical info
 */
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
});

/**
 * JetBrains Mono - Alternative monospace
 */
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: "#0a0a0a",
};

export const metadata: Metadata = {
  metadataBase: new URL("https://yt.pcstyle.dev"),
  title: "yT3 Chat - YouTube Live Chat Viewer",
  description: "A premium, customizable YouTube Live Chat viewer. Two modes: minimal OBS overlay and full-featured dashboard. Built for streamers and viewers alike.",
  keywords: ["YouTube", "Live Chat", "Streamer", "OBS", "Chat Viewer", "t3dotgg"],
  authors: [{ name: "yT3 Chat" }],
  creator: "yT3 Chat",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://yt.pcstyle.dev",
    siteName: "yT3 Chat",
    title: "yT3 Chat - YouTube Live Chat Viewer",
    description: "Premium YouTube Live Chat viewer with customizable themes, OBS overlay mode, and zero-cost demo mode.",
    // Dynamic OG image generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "yT3 Chat - YouTube Live Chat Viewer",
    description: "Premium YouTube Live Chat viewer. Perfect for streamers and chat enthusiasts.",
    // Dynamic Twitter image generated by twitter-image.tsx
    creator: "@t3dotgg",
  },
  robots: {
    index: true,
    follow: true,
  },
  // Icons are now dynamic via icon.tsx and apple-icon.tsx
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${geist.variable} ${geistMono.variable} ${jetbrainsMono.variable}`} suppressHydrationWarning>
      <body className="antialiased">
        <CustomizationProvider>
          {children}
        </CustomizationProvider>
      </body>
    </html>
  );
}
